// GENEROITU TIEDOSTO — älä muokkaa käsin.
// Lähde: sivujen <head>-metatiedot (kortti-otsikko, kortti-kuvaus, tagit, robots).
// Päivitä ajamalla: python3 tyokalut/rakenna.py

window.SIVUSTO_TAGIT = {"ai": "AI", "arkkitehtuuri": "arkkitehtuuri", "dax": "DAX", "hallinta": "hallinta", "kesken": "Kesken", "kirjallisuus": "kirjallisuus", "perusteoria": "perusteoria", "poikkeustapaus": "poikkeustapaus", "power-bi": "Power BI", "tietomalli": "tietomalli", "tyokalut": "työkalut"};

window.SIVUT = {
  "ai-valmis-metadata.html": {"otsikko": "AI-valmis metadata", "kuvaus": "Mitä tauluista, sarakkeista ja mittareista kannattaa kuvata tietovarastossa ja Power BI:ssä, jotta Copilot ja muut AI-työkalut toimivat luotettavasti.", "tagit": ["hallinta", "power-bi", "ai", "tietomalli"], "min": 10, "julkaistu": true, "badge": null},
  "apuohjelmat.html": {"otsikko": "Apuohjelmat", "kuvaus": "DAX Studio, Tabular Editor, ALM Toolkit ja Power BI MCP — Power BI -kehittäjän tärkeimmät lisätyökalut selitettynä.", "tagit": ["tyokalut", "power-bi", "dax", "ai"], "min": 9, "julkaistu": true, "badge": null},
  "arkkitehtuurivalinta.html": {"otsikko": "Milloin käyttää mitäkin mallia", "kuvaus": "Vertailutaulukot ja käytännön ohjeet: tähtimalli, lumihiutalemalli, Data Vault, Data Mesh, ETL ja ELT — milloin kukin on hyvä, milloin huono ja miksi.", "tagit": ["arkkitehtuuri", "tietomalli", "perusteoria"], "min": 13, "julkaistu": false, "badge": null},
  "avaimet-ja-relaatiot.html": {"otsikko": "Avaimien ja relaatioiden mallinnus", "kuvaus": "Avaintyypit (PK, FK, surrogaatti, degeneraatioavain), relaatioiden kardinaliteetti ja suodatussuunta sekä orpojen vierasavainten käsittely sentinel-rivein.", "tagit": ["tietomalli", "power-bi", "perusteoria"], "min": 12, "julkaistu": true, "badge": null},
  "data-contract.html": {"otsikko": "Data Contract", "kuvaus": "Sopimus datan tuottajan ja kuluttajan välillä. Määrittelee mitä dataa toimitetaan, missä muodossa, millä laadulla ja kenen vastuulla.", "tagit": ["hallinta", "perusteoria"], "min": 16, "julkaistu": false, "badge": null},
  "data-governance.html": {"otsikko": "Data Governance", "kuvaus": "Datan omistajuus, laadunvarmistus, metadatan hallinta, elinkaari ja tietosuoja. Vastaukset keskeisimpiin hallintakysymyksiin dataneuvoksen suosituksineen.", "tagit": ["hallinta", "perusteoria"], "min": 8, "julkaistu": false, "badge": null},
  "data-vault.html": {"otsikko": "Data Vault", "kuvaus": "Skaalautuva ja auditoitava tietovarastoarkkitehtuuri. Perustuu hub-, satellite- ja link-tauluihin. Sopii erityisesti historiallisten tietojen hallintaan.", "tagit": ["arkkitehtuuri", "tietomalli"], "min": 3, "julkaistu": false, "badge": null},
  "dimensiot.html": {"otsikko": "Dimensioiden mallinnus", "kuvaus": "Surrogaattiavaimet, SCD-tyypit 0–6, parhaat käytännöt ja Power BI:n suorituskykyrajat eri kokoisilla dimensioilla.", "tagit": ["tietomalli", "power-bi", "perusteoria"], "min": 14, "julkaistu": true, "badge": null},
  "etl-elt.html": {"otsikko": "ETL ja ELT", "kuvaus": "Kaksi päälähestymistapaa datan siirtämiseen lähdejärjestelmistä kohdeympäristöön. Missä ja milloin data muunnetaan?", "tagit": ["arkkitehtuuri", "perusteoria"], "min": 1, "julkaistu": false, "badge": null},
  "faktataulu.html": {"otsikko": "Faktataulun mallinnus", "kuvaus": "Faktataulun rakenne, kolme arkkityyppiä ja granulariteetin valinta. Vierasavaimet, additiivisuus ja kultaiset säännöt Power BI -tietomallia varten.", "tagit": ["tietomalli", "power-bi", "perusteoria"], "min": 13, "julkaistu": true, "badge": null},
  "header-detail.html": {"otsikko": "Header-Detail-malli", "kuvaus": "Malli tapahtumatietojen hallintaan, jossa otsikkotaulu (esim. tilaus) ja rivitaulu (esim. tilausrivit) ovat erillään.", "tagit": ["tietomalli", "power-bi", "poikkeustapaus"], "min": 3, "julkaistu": false, "badge": null},
  "intentiovelka.html": {"otsikko": "Intentiovelka dataympäristössä", "kuvaus": "Intentiovelka on kirjaamatta jäänyt perustelu: kukaan ei enää tiedä miksi mittarissa on juuri ne rajaukset. Näin se syntyy ja näin sen maksaa pois.", "tagit": [], "min": 11, "julkaistu": false, "badge": null},
  "kehittamisen-filosofia.html": {"otsikko": "Kehittämisen filosofia", "kuvaus": "Periaatteita, jotka ohjaavat hyvää BI-kehitystä: ylläpidettävyys, avoimuus ongelmista, tekninen velka ja käyttäjälähtöisyys.", "tagit": ["hallinta", "perusteoria"], "min": 1, "julkaistu": true, "badge": null},
  "kirjallisuus-suositukset.html": {"otsikko": "Suositeltu kirjallisuus", "kuvaus": "Parhaat kirjat datan mallinnuksesta, tietovarastoinnista ja Power BI:stä. Hyvä lukupaketti niin aloittelijoille kuin kokeneille.", "tagit": ["kirjallisuus", "dax", "tietomalli"], "min": 8, "julkaistu": true, "badge": null},
  "litistaminen.html": {"otsikko": "Taulujen litistäminen (Flattening)", "kuvaus": "Hierarkkisten dimensiotaulujen yhdistäminen yhdeksi leveäksi tauluksi ennen Power BI -latausta. Muuttaa lumihiutaleen tähtimalliksi.", "tagit": ["tietomalli", "power-bi", "perusteoria"], "min": 4, "julkaistu": true, "badge": null},
  "lumihiutalemalli.html": {"otsikko": "Lumihiutalemalli (Snowflake Schema)", "kuvaus": "Tähtimallin laajennus, jossa dimensiot on normalisoitu useampaan tauluun. Vähentää toisteisuutta mutta lisää monimutkaisuutta.", "tagit": ["tietomalli", "power-bi", "perusteoria"], "min": 3, "julkaistu": true, "badge": null},
  "medallion.html": {"otsikko": "Medallion-arkkitehtuuri", "kuvaus": "Datan jalostaminen kerroksittain: Bronze (raakadata), Silver (puhdistettu) ja Gold (liiketoimintavalmis). Yleinen data lake -ympäristöissä.", "tagit": ["arkkitehtuuri", "perusteoria"], "min": 11, "julkaistu": true, "badge": "uutuus"},
  "nimeamiskaytannot.html": {"otsikko": "Nimeämiskäytännöt", "kuvaus": "Ferrarin ja Russon seitsemän sääntöä taulujen ja sarakkeiden nimeämiseen Power BI -tietomalleissa. Selkeys alkaa nimistä.", "tagit": ["hallinta", "power-bi", "tietomalli"], "min": 7, "julkaistu": true, "badge": null},
  "palvelut.html": {"otsikko": "Palvelut", "kuvaus": "Tietomallin kuntotarkastus, suorituskykyselvitys, arkkitehtuurin toinen mielipide ja jatkuva sparraus — rajattuina paketteina, hinta-arvioineen.", "tagit": ["tietomalli", "power-bi"], "min": 4, "julkaistu": true, "badge": null},
  "sekasikiomalli-vs-tahtimalli.html": {"otsikko": "Sekasikiömalli vs tähtimalli", "kuvaus": "Orgaanisesti kasvanut sekasikiömalli ja siivottu tähtimalli vastaavat samoihin kysymyksiin. Vertailu näyttää, miksi tähtimalli on silti nopeampi, varmempi ja AI-valmis.", "tagit": ["tietomalli", "power-bi", "ai"], "min": 15, "julkaistu": true, "badge": null},
  "surrogaattiavaimet.html": {"otsikko": "Surrogaattiavaimien mallintaminen", "kuvaus": "Missä medallion-kerroksessa surrogaattiavaimet luodaan, miten suuria dimensioita hallitaan ja kuinka inkrementaalinen lataus toimii käytännössä.", "tagit": ["tietomalli", "power-bi", "perusteoria"], "min": 16, "julkaistu": true, "badge": "uutuus"},
  "tahtimalli.html": {"otsikko": "Tähtimalli (Star Schema)", "kuvaus": "Yksinkertainen ja suorituskykyinen malli, jossa faktataulun ympärille liitetään dimensiotaulut suoraan. Yleisin valinta BI-ratkaisuissa.", "tagit": ["tietomalli", "power-bi", "perusteoria", "ai"], "min": 6, "julkaistu": true, "badge": null},
  "termisto.html": {"otsikko": "Termistö", "kuvaus": "Datan mallinnuksen, tietovarastoinnin ja BI-kehittämisen termit aakkosjärjestyksessä. Lyhyet selitykset suomeksi, englanninkieliset vastineet mukana.", "tagit": ["perusteoria", "tietomalli"], "min": 27, "julkaistu": true, "badge": null},
  "tietoa.html": {"otsikko": "Tietoa sivustosta", "kuvaus": "Kuka datamalli.fi:n takana on ja mihin sivusto tähtää — tekijänä Samu Lahdenperä (Dataneuvos), 10+ v. analytiikka- ja BI-kokemus.", "tagit": [], "min": 3, "julkaistu": true, "badge": null},
  "tietomalli.html": {"otsikko": "Tietomalli", "kuvaus": "Mikä tietomalli on, mitä eroa on käsitemallilla, loogisella ja fyysisellä mallilla ja mistä tietomallinnus aloitetaan. Aloitussivu koko aiheeseen.", "tagit": ["tietomalli", "perusteoria", "power-bi"], "min": 7, "julkaistu": true, "badge": null},
  "useampi-fakta.html": {"otsikko": "Useamman faktataulun malli", "kuvaus": "Useamman faktataulun yhdistäminen yhteisten dimensioiden avulla. Mahdollistaa eri liiketoimintaprosessien vertailun.", "tagit": ["tietomalli", "power-bi", "dax", "poikkeustapaus"], "min": 2, "julkaistu": false, "badge": null},
};
